# Change these first
owner: kreatoo # Your GitHub organization or username, where this repository lives
repo: kreatea-status # The name of this repository

sites:
  - name: Main website
    url: https://kreatea.space
  - name: Gitea
    url: https://git.kreatea.space
  - name: Matrix (Synapse)
    url: https://matrix.kreatea.space
  - name: Nextcloud
    url: https://cloud.kreatea.space
  - name: Searx
    url: https://searx.kreatea.space
  - name: Teddit
    url: https://t.kreatea.space
  - name: Nitter
    url: https://nitter.kreatea.space

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kreatea.space
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Kreatea Status
  introTitle: "Kreatea status page."
  navbar:
    - title: Status
      href: /
    - title: Main site
      href: https://kreatea.space
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
